language: php
php:
    - 5.6
    - hhvm
    - nightly



matrix:
    allow_failures:
        - php: '7.0'
        - php: '7.1'
        - php: '5.5'
        - php: '5.4'
        - php: hhvm
        - php: nightly



before_script:
    - wget https://scrutinizer-ci.com/ocular.phar


script: 
    - phpunit --bootstrap test/config.php --coverage-clover=coverage.clover test



after_script:
    - php ocular.phar code-coverage:upload --access-token="29b75d071491d67a6275358b794a5ea1196100f4be409f4077903e97b7f07a55" --format=php-clover coverage.clover
